# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('will_attend', models.BooleanField(default=True, verbose_name='will attend')),
                ('guest2', models.CharField(max_length=100, verbose_name='Name, Surname')),
                ('guest3', models.CharField(max_length=100, verbose_name='Name, Surname')),
                ('guest4', models.CharField(max_length=100, verbose_name='Name, Surname')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
            },
        ),
    ]
