# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='guest2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name, Surname'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='guest3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name, Surname'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='guest4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name, Surname'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='will_attend',
            field=models.NullBooleanField(verbose_name='Attendance'),
        ),
    ]
