# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_auto_20170410_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'permissions': (('edit', 'Can edit the Gift list'),), 'verbose_name': 'Gift', 'verbose_name_plural': 'Gifts'},
        ),
    ]
