# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_auto_20170411_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftorder',
            name='payment_received',
            field=models.BooleanField(default=False, verbose_name='Payment received'),
        ),
        migrations.AddField(
            model_name='giftorder',
            name='voucher_issued',
            field=models.BooleanField(default=False, verbose_name='Voucher issued'),
        ),
    ]
