# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_auto_20170413_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total price'),
        ),
        migrations.AddField(
            model_name='giftorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='giftorderitem',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.Gift'),
        ),
    ]
