# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='street1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Street 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='street2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Street 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='ZIP'),
        ),
    ]
