# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='headline',
            field=models.CharField(default='Contact us', max_length=255),
        ),
    ]
