# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 18:46
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20161214_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('CoupleBlock', wagtail.wagtailcore.blocks.StructBlock((('maintitle', wagtail.wagtailcore.blocks.CharBlock()), ('subtitle', wagtail.wagtailcore.blocks.CharBlock()), ('headline', wagtail.wagtailcore.blocks.CharBlock()), ('bridename', wagtail.wagtailcore.blocks.CharBlock()), ('bridetext', wagtail.wagtailcore.blocks.TextBlock()), ('bridephoto', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('groomame', wagtail.wagtailcore.blocks.CharBlock()), ('groomtext', wagtail.wagtailcore.blocks.TextBlock()), ('groomphoto', wagtail.wagtailimages.blocks.ImageChooserBlock())))),), default=''),
        ),
    ]
