# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 22:23
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20161223_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('CoupleBlock', wagtail.wagtailcore.blocks.StructBlock((('maintitle', wagtail.wagtailcore.blocks.CharBlock()), ('subtitle', wagtail.wagtailcore.blocks.CharBlock()), ('headline', wagtail.wagtailcore.blocks.CharBlock()), ('bridename', wagtail.wagtailcore.blocks.CharBlock()), ('bridetext', wagtail.wagtailcore.blocks.TextBlock()), ('bridephoto', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('groomame', wagtail.wagtailcore.blocks.CharBlock()), ('groomtext', wagtail.wagtailcore.blocks.TextBlock()), ('groomphoto', wagtail.wagtailimages.blocks.ImageChooserBlock())))), ('TwoColumnBlock', wagtail.wagtailcore.blocks.StructBlock((('background', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('theme-white', 'White'), ('theme-black', 'Black'), ('theme-darker', 'Dark Gray'), ('theme-body-color', 'Body Color'), ('theme-primary', 'Primary Color'), ('theme-secondary', 'Secondary Color')], default='white')), ('left_column', wagtail.wagtailcore.blocks.StreamBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('google_map', wagtail.wagtailcore.blocks.StructBlock((('map_width', wagtail.wagtailcore.blocks.CharBlock(default='600', max_length=4, required=True)), ('map_height', wagtail.wagtailcore.blocks.CharBlock(default='450', max_length=4, required=True)))))), icon='arrow-left', label='Left column content')), ('right_column', wagtail.wagtailcore.blocks.StreamBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('google_map', wagtail.wagtailcore.blocks.StructBlock((('map_width', wagtail.wagtailcore.blocks.CharBlock(default='600', max_length=4, required=True)), ('map_height', wagtail.wagtailcore.blocks.CharBlock(default='450', max_length=4, required=True)))))), icon='arrow-right', label='Right column content'))))), ('GoogleMapBlock', wagtail.wagtailcore.blocks.StructBlock((('map_width', wagtail.wagtailcore.blocks.CharBlock(default='600', max_length=4, required=True)), ('map_height', wagtail.wagtailcore.blocks.CharBlock(default='450', max_length=4, required=True))))), ('RichTextBlock', wagtail.wagtailcore.blocks.RichTextBlock())), default=''),
        ),
    ]
