# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_accommodation_goodtoknow_ourdaypage_ourwish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accommodation',
            new_name='AccommodationPage',
        ),
        migrations.RenameModel(
            old_name='GoodToKnow',
            new_name='GoodToKnowPage',
        ),
        migrations.RenameModel(
            old_name='OurWish',
            new_name='OurWishPage',
        ),
    ]
