# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 15:30
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20161230_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourdaypage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('MainTitle', wagtail.wagtailcore.blocks.StructBlock((('maintitle', wagtail.wagtailcore.blocks.CharBlock()),))), ('Paragraph', wagtail.wagtailcore.blocks.StructBlock((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()),))), ('Image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('endtoend', wagtail.wagtailcore.blocks.BooleanBlock()), ('width', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('original', 'original'), ('1920', '1920'), ('800', '800'), ('640', '640'), ('400', '400')], default='800'))))), ('TwoColumnBlock', wagtail.wagtailcore.blocks.StructBlock((('background', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('theme-white', 'White'), ('theme-black', 'Black'), ('theme-darker', 'Dark Gray'), ('theme-body-color', 'Body Color'), ('theme-primary', 'Primary Color'), ('theme-secondary', 'Secondary Color')], default='white')), ('left_column', wagtail.wagtailcore.blocks.StreamBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('google_map', wagtail.wagtailcore.blocks.StructBlock((('map_width', wagtail.wagtailcore.blocks.CharBlock(default='600', max_length=4, required=True)), ('map_height', wagtail.wagtailcore.blocks.CharBlock(default='450', max_length=4, required=True)), ('map_params', wagtail.wagtailcore.blocks.CharBlock(help_text='No spaces, add + instead', max_length=300, required=True)))))), icon='arrow-left', label='Left column content')), ('right_column', wagtail.wagtailcore.blocks.StreamBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('google_map', wagtail.wagtailcore.blocks.StructBlock((('map_width', wagtail.wagtailcore.blocks.CharBlock(default='600', max_length=4, required=True)), ('map_height', wagtail.wagtailcore.blocks.CharBlock(default='450', max_length=4, required=True)), ('map_params', wagtail.wagtailcore.blocks.CharBlock(help_text='No spaces, add + instead', max_length=300, required=True)))))), icon='arrow-right', label='Right column content'))))), ('EventBlock', wagtail.wagtailcore.blocks.StructBlock((('background', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('headline', wagtail.wagtailcore.blocks.CharBlock()), ('maintitle', wagtail.wagtailcore.blocks.CharBlock()), ('lefttitle', wagtail.wagtailcore.blocks.CharBlock()), ('lefttime', wagtail.wagtailcore.blocks.CharBlock()), ('leftdate', wagtail.wagtailcore.blocks.CharBlock()), ('lefttext', wagtail.wagtailcore.blocks.TextBlock()), ('righttitle', wagtail.wagtailcore.blocks.CharBlock()), ('righttime', wagtail.wagtailcore.blocks.CharBlock()), ('rightdate', wagtail.wagtailcore.blocks.CharBlock()), ('righttext', wagtail.wagtailcore.blocks.TextBlock()))))), default=''),
        ),
    ]
